void viderGrille ();
void assurerGrilleJouable ();
int verifierAbsencesFiduresInitiales ();
void eliminerSuiteEnLigne(int ligne, int colonne, int taille);
void eliminerSuiteEnColonne(int ligne, int colonne, int taille);
void eliminerCarre (int ligne, int colonne);
void eliminerCroix (int ligne, int colonne);
void eliminerFigure (int type, int ligne, int colonne, int taille);
void appliquerGravite ();
void melangerItems ();
int jeu (int temps_restant);
void genererItems(char grille[10][9]);
void gererContrat(char item, int *x, int *o, int *et, int *at, int *pourcent);
void malus(int *coups);
void gererVictoirePartie(void);
void gererEchecPartie(void);
