void viderGrille ();
void assurerGrilleJouable ();
int verifierAbsencesFiduresInitiales ();
ResultatFigure detecterSuiteEnLigne();
ResultatFigure detecterSuiteEnColonne();
ResultatFigure detecterCroix();
ResultatFigure detecterCarre();
ResultatFigure detecterFigure();
void eliminerSuiteEnLigne(int ligne, int colonne, int taille);
void eliminerSuiteEnColonne(int ligne, int colonne, int taille);
void eliminerCarre (int ligne, int colonne);
void eliminerCroix (int ligne, int colonne);
void eliminerFigure (int type, int ligne, int colonne, int taille);
void appliquerGravite ();
void melangerItems ();
int jeu (int temps_restant);
void genererItems(char grille[HAUTEUR][LARGEUR]);
void gererContrat(char item, int *x, int *o, int *et, int *at, int *pourcent);
void malus(int *coups);
void gererVictoirePartie(void);
void gererEchecPartie(void);
void quitterProgramme(void);
int gererContrat(int *x, int *o, int *et, int *at, int *pourcent, char item, int taille);
